#!/bin/bash
# run-tests.sh — Lance la suite de tests complète de cl-asm.
# Doit être exécuté depuis la racine du projet (le répertoire cl-asm/).

sbcl --load src/core/version.lisp \
     --load src/core/backends.lisp \
     --load src/core/disassemblers.lisp \
     --load src/core/ir.lisp \
     --load src/core/debug-map.lisp \
     --load src/core/expression.lisp \
     --load src/core/symbol-table.lisp \
     --load src/frontend/classic-lexer.lisp \
     --load src/frontend/classic-parser.lisp \
     --load src/backend/6502.lisp \
     --load src/backend/6510.lisp \
     --load src/backend/45gs02.lisp \
     --load src/emit/output.lisp \
     --load src/backend/65c02.lisp \
     --load src/backend/r65c02.lisp \
     --load src/backend/65816.lisp \
     --load src/backend/z80.lisp \
     --load src/backend/m68k.lisp \
     --load src/backend/i8080.lisp \
     --load src/frontend/lasm.lisp \
     --load src/simulator/6502.lisp \
     --load src/disassembler/6502.lisp \
     --load src/disassembler/45gs02.lisp \
     --load src/disassembler/65c02.lisp \
     --load src/debugger/6502.lisp \
     --load tests/test-debugger-6502.lisp \
     --load tests/test-65c02.lisp \
     --load tests/test-r65c02.lisp \
     --load tests/test-lasm.lisp \
     --load tests/test-conditional.lisp \
     --load tests/test-macros.lisp \
     --load tests/test-45gs02.lisp \
     --load tests/test-6510.lisp \
     --load tests/test-6502.lisp \
     --load tests/test-parser.lisp \
     --load tests/test-lexer.lisp \
     --load tests/test-expression.lisp \
     --load tests/test-symbol-table.lisp \
     --load tests/test-65816.lisp \
     --load tests/test-z80.lisp \
     --load tests/test-m68k-parser.lisp \
     --load tests/test-m68k.lisp \
     --load tests/test-8080.lisp \
     --load tests/test-sim-6502.lisp \
     --load tests/test-sim-programs.lisp \
     --load tests/test-acme2clasm.lisp \
     --load tests/test-disasm-6502.lisp \
     --load tests/test-disasm-45gs02.lisp \
     --load tests/test-disasm-65c02.lisp \
     --load tests/run-tests.lisp \
     --eval "(cl-asm/test:run-all-tests)" \
     --quit
